# Generated by Django 4.2.1 on 2023-08-07 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email of the venue')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Contacts number')),
                ('web', models.URLField(blank=True, verbose_name='Web page')),
                ('desc', models.TextField(blank=True)),
                ('owner', models.IntegerField(default=1, verbose_name='Venue Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('desc', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.venue')),
                ('visitors', models.ManyToManyField(blank=True, to='event.myclubuser')),
            ],
        ),
    ]
