# Generated by Django 4.2.4 on 2023-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_event_visitors"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="venue_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
